### ISSUE TITLE
wtf is gui key?

### ISSUE THREAD

**Issue by Fiyxz** [MrsRina/onepop#5]
p;z helpp

**Comment by Fiyxz** [comment]
plz help

**Comment by Fiyxz** [comment]
Just went into files and changed it

**Comment by Fiyxz** [comment]
nvm didn't work still need to know the gui key

**Comment by Fiyxz** [comment]
finally got it smh

**Comment by master7720** [comment]
bruh

**Comment by mrsrina** [comment]
There is no bind for default. You need type '.t clickgui'

**Comment by mrsrina** [comment]
With clickgui module toggled, just bind it.
